url: https://www.josephguadagno.net
name: JosephGuadagno.net - Microsoft .NET MVP, Team Leader at Quicken Loans, Organizer of Desert Code Camp
title: JosephGuadagno.net - Microsoft .NET MVP, Team Leader at Quicken Loans, Organizer of Desert Code Camp
description: >
  Microsoft .NET MVP, Team Leader at
  Quicken Loans, Organizer of Desert Code
  Camp
permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
sass:
    load_paths:
        - _sass
        - node_modules
exclude: []
plugins:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-redirect-from
   - jekyll-seo-tag
   - jekyll-sitemap
   - jekyll-avatar
   - jemoji
   - jekyll-mentions
   - jekyll-gist
theme: jekyll-theme-leap-day