version: '3.7'

services:
  Jekyll: #https://github.com/envygeeks/jekyll-docker
    image: jekyll/jekyll:latest
    container_name: jekyll
    restart: always
    environment: 
      JEKYLL_GITHUB_TOKEN: ${JEKYLL_GITHUB_TOKEN}
    command: jekyll serve --watch --incremental --force_polling
    ports:
      - 4000:4000
    volumes:
      # - /Users/JGuadagno/Projects/jguadagno.github.io:/srv/jekyll #Mac
      - c:/Projects/jguadagno.github.io:/srv/jekyll #Windows
